version: "3.9"

services:
  db:
    image: postgis/postgis:latest
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker/dev/.env
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      retries: 10
  backend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.backend.dev
    restart: on-failure
    env_file:
      - docker/dev/.env
    expose:
      - 8082
    ports:
      - 8082:8082
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

volumes:
  pgdata:
