# Generated by Django 4.2.7 on 2023-11-24 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("age", models.SmallIntegerField()),
                ("occupation", models.CharField(max_length=256)),
                (
                    "annual_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monthly_inhand_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("num_bank_accounts", models.IntegerField()),
                ("num_of_loan", models.IntegerField()),
                ("num_credit_inquiries", models.IntegerField()),
                ("credit_history_age", models.IntegerField()),
                (
                    "amount_invested_monthly",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "payment_behaviour",
                    models.CharField(
                        choices=[
                            (
                                "Low_spent_Small_value_payments",
                                "Мало потратил, малые платежи",
                            ),
                            (
                                "Low_spent_Medium_value_payments",
                                "Мало потратил, средние платежи",
                            ),
                            (
                                "Low_spent_Large_value_payments",
                                "Мало потратил, большие платежи",
                            ),
                            (
                                "High_spent_Small_value_payments",
                                "Много потратил, малые платежи",
                            ),
                            (
                                "High_spent_Medium_value_payments",
                                "Много потратил, средние платежи",
                            ),
                            (
                                "High_spent_Large_value_payments",
                                "Много потратил, большие платежи",
                            ),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "monthly_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("allow_credit", models.BooleanField(default=None)),
            ],
        ),
    ]
