# Generated by Django 4.2.7 on 2023-11-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_application", "0002_alter_creditapplication_allow_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditapplication",
            name="credit_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creditapplication",
            name="num_credit_card",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="creditapplication",
            name="username",
            field=models.CharField(default="", max_length=128),
        ),
    ]
